config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "landing_page#index"

  resources :landing_page, path: '/', only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController

  def index
    render 'layouts/landing_page'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing_page/index.html.erb
<h1> Oi </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TiConsultoria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <%= render 'layouts/landing_page/header'%>

  <body>
    <div class="container-fluid">
      <header class="home" id="topo">
        <div class="container">
          <%= render 'layouts/landing_page/menu_home'%>

          <div class="row">
            <a href='<%= landing_page_index_path %>'>
              <%= image_tag("logo.png", :alt => "Logo TiConsultoria", :class => "img-responsive center-block", style: "height: 120px; width: 120px;") %>
            </a>
            <h1>Conectando especialistas na aréa de tecnologia para resolver seu problema</h1>

            <div class="more-info">
              <a class="anchorLink" href="#teste" data-hover="teste">
                SAIBA MAIS<br />
                <%= image_tag("ic_arrowdown.svg", :alt => "icon_arrow_down") %> 
              </a>
            </div>
          </div>
        </div>

        <div class="row last-row">
          <span class="txt">Disponível para</span>
          <a href="" target="_blank">
            <%= image_tag("btn_android.svg", :alt => "TiConsultoria Android") %>
          </a>
          <a href="" target="_blank">
            <%= image_tag("btn_ios.svg", :alt => "TiConsultoria iOS") %>
          </a>
        </div>
      </header>

      <div class="rancher-card col-12 container" id="teste">
        <div class="col-xs-12 col-sm-12 col-md-5 offset-md-1">
          <div class="row">
            <h4>TiConsultoria</h4>
            <p>É uma consultoria que presta manutenção na área de TI. Tome um dos nossos deliciosos cafés enquanto fazemos manutenção de seu sistema</p>
          </div>

          <div class="row">
            <div class="buttons-container">
              <div class="row">
                <div class="rancher-links">
                  <a href="" class="btn btn-success rancher" target="_blank">Trocar</a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="smartphone d-none d-sm-block d-md-block">
          <!-- < %= image_tag("img_devices.png", :alt => "TiConsultoria Devices", :class => "img-responsive") %> -->
        </div>
      </div>

      <div class="why-ticonsultoria-card col-12">
        <div class="container">
          <h4>POR QUÊ ESCOLHER O TICONSULTORIA?</h4>
          <p>Bla bla bla bla bla.</p>
        </div>

        <div class="container">
          <div class="row">
            <div class="col-xs-4 col-sm-10 col-md-3 small-card first-card">
              <!-- < %= image_tag("ic_paravc_1.svg", :alt => "") %> -->
              <h4>SOMOS FODAS</h4>
              <p>Dolor sit amet, consectetur adipiscing elit. Integer ex est, hendrerit ac volutpat nec, dictum ac turpis. Maecenas in condimentum velit, nec rutrum leo. Maecenas in condimentum velit, nec rutrum leo.</p>
            </div>

            <div class="col-xs-4 col-sm-10 col-md-3 small-card">
              <!-- < %= image_tag("ic_paravc_2.svg", :alt => "") %> -->
              <h4>PICAS</h4>
              <p>Dolor sit amet, consectetur adipiscing elit. Integer ex est, hendrerit ac volutpat nec, dictum ac turpis. Maecenas in condimentum velit, nec rutrum leo. Maecenas in condimentum velit, nec rutrum leo.</p>
            </div>

            <div class="col-xs-4 col-sm-10 col-md-3 small-card">
              <!-- < %= image_tag("ic_paravc_3.svg", :alt => "") %> -->
              <h4>FODAS</h4>
              <p>Dolor sit amet, consectetur adipiscing elit. Integer ex est, hendrerit ac volutpat nec, dictum ac turpis. Maecenas in condimentum velit, nec rutrum leo. Maecenas in condimentum velit, nec rutrum leo.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%= render 'layouts/landing_page/footer'%>
  </body>
</html>

app/views/layouts/landing_page/_footer.html.erb
<footer class="col-12">
  <div class="col-4 offset-1 offset-md-2 footer-menu">
    <!-- < %= link_to "Políticas de Privacidade", privacy_policies_path %> -->
    
  </div>

  <div class="col-5 offset-6 offset-md-5">
    <p class="developed-by">Desenvolvido por Estácio TADS<br></p>
  </div>

  <div class="col-4 offset-1 offset-md-2">
    <p class="copyright">© Copyright 2019 por TiConsultoria. Todos os direitos reservados.<br></p>
  </div>
</footer>

app/views/layouts/landing_page/_header.html.erb
<head>
  <meta charset="utf-8">

  <title>TiConsultoria</title>
  <html lang="pt-br">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5">
  <meta name="description" content="É uma consultoria que presta manutenção na área de TI. Tome um dos nossos deliciosos cafés enquanto fazemos manutenção de seu sistema">

  <meta name="theme-color" content="#188bf1">
  <meta name="msapplication-navbutton-color" content="#188bf1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

  <%= favicon_link_tag '/ic_favicon.png', rel: 'icon', type: 'image/png' %>

  <!-- BOOTSTRAP 4.0 -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <%= stylesheet_link_tag 'landing_page', media: 'all' %>
  <%= javascript_include_tag 'landing_page', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/landing_page/_menu_home.html.erb
<nav class="navbar navbar-home navbar-expand-lg navbar-dark fixed-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a href="#topo" class="anchorLink active nav-link text-uppercase" data-hover="para você">para você</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-uppercase anchorLink" href="#todo" data-hover="todo">seila</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-uppercase anchorLink" href="#todo" data-hover="todo">seila</a>
      </li>
      <li class="nav-item active only-mobile">
      </li>
    </ul>
    <div class="info">
      <span>contato:<br /></span>
      contato@ticonsultoria.com
    </div>
  </div>
</nav>

app/views/layouts/landing_page/_menu_secondary.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top menu-scroll">
  <div class="container">
    <a class="navbar-brand" href='<%= landing_page_index_path %>'><%= image_tag("logo_h.svg", :alt => "Logo TiConsultoria") %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link text-uppercase" href='<%= landing_page_index_path %>'>home</a>
        </li>
      </ul>
      <div class="info">
        <span>contato:<br /></span>
        contato@ticonsultoria.com
      </div>
      <div class="info">
        <span>telefone:<br /></span>
        (67) 99999-9999
      </div>
    </div>
  </div>
</nav>